TYPO3:
  Flow:
    security:
      authentication:
        providers:
          OneClickProvider:
            provider: 'Netlogix\OneClickSignOn\Security\Authentication\Provider\OneClickProvider'
            requestPatterns:
            providerOptions:
              useProviderName: 'DefaultProvider'